---
version: 2
updates:

  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
      time: '04:20'
    target-branch: master

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '04:20'
    target-branch: master
